[workspace]
resolver = "2"
members = ["crates/*"]
default-members = ["crates/legit"]

[workspace.package]
authors = ["Lucas Vieira dos Santos <lucas6eng@gmail.com>"]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
legit = { path = "crates/legit" }
